# -*- coding: utf-8 -*-
"""Trabalho ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jROpL9B6gPWjPTlWHzz7wZopphK4a4sw

# Detecção de Spam em E-mails

Discipina: Machine Learning - Teoria e Aplicado\
Professora: Ma. Nathália A. Lima\
Grupo:15

Integrantes:
- João Pedro Torres - 2007848
- João Pedro Duarte - 1993686
- Mateus Felix - 1998770

# Descrição do Dataset
Fonte: Kaggle\
Dataset: Spambase\
Cada linha corresponde a um e-mail e cada coluna representa uma caracteristica especifica do email como a frequencia de palavras comuns e caracteres especiais e a coluna "spam" indica se um email é spam(1) ou é uma mensagem verdadeira(0)

----------

# Importações
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, ConfusionMatrixDisplay,
    roc_curve
)
print("As bibliotecas foram carregadas com sucesso!")

"""# Carregando o Dataset"""

print("Dataset carregdao com sucesso!")
df = pd.read_csv('spambase_updated.csv')
df

"""# Etapa 1 - Análise Exploratória (EDA)

# 1.1 Análise da base de dados
"""

df.info()

"""# 1.2 Verificação da quantidade de spams e hams na base de dados

"""

print("Quantididade de Spams e Hams no Dataset")
spams_hams = df.groupby('spam')['spam'].count()
spams_hams

plt.figure(figsize=(10,6))
spams_hams.plot(kind='bar')
plt.title("Quantidade de Spams x Hams")

spams_hams.plot(kind='pie', autopct='%1.1f%%', startangle=90)
plt.title("Quantidade de Spams x Hams")

"""# 1.3 Estatísticas descritivas"""

print("Descrição do dataframe")
df.describe()

"""# 1.4 Identificação de valores nulos"""

# Identificar se existem valores nulos
df.isnull().sum().sort_values(ascending=False).head()

"""# 1.5 Variáveis que mais ajudam a detectar Spam"""

X = df.drop('spam', axis=1)
y = df['spam']
grafico = RandomForestClassifier().fit(X, y)

importantes = pd.Series(grafico.feature_importances_, index=X.columns)
importantes.nlargest(15).plot(kind='barh')
plt.title("Variáveis que mais ajudam a detectar Spam")

"""# 1.6 Variáveis que mais se correlacionam com Spam"""

top_5 = df.corr()['spam'].sort_values(ascending=False).index[1:6]
sns.pairplot(df, vars=top_5, hue='spam', palette='coolwarm')

"""# Etapa 2 - Pré-processamento

# 2.1 Limpeza de valores nulos e duplicados
"""

print("Valores nulos:", df.isnull().sum().sum())
print("Duplicados:", df.duplicated().sum())

print(f"Formato da tabela original: {df.shape}")
df = df.drop_duplicates()
df = df.dropna()
print(f"Formato da tabela após a limpeza: {df.shape}")

"""# 2.2 Separação das features (X)"""

x = df.iloc[:, 0:57]
x

"""# 2.3 Separação dos targets (Y)"""

y = df['spam']
y

"""# 2.3 Divisão de treino, teste e validação"""

x_temp, x_test, y_temp, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=42)
x_train, x_val, y_train, y_val = train_test_split(x_temp, y_temp, test_size=0.25, stratify=y_temp, random_state=42)

"""
# 2.4 Redimensionamento de dados

"""

scaler = StandardScaler()

X_train_std = scaler.fit_transform(x_train)
X_test_std = scaler.transform(x_test)

mm_scaler = MinMaxScaler()
X_train_mm = mm_scaler.fit_transform(x_train)
X_test_mm = mm_scaler.transform(x_test)

"""# Etapa 3 - Comparação de Modelos

# 3.1 Criação do dicionário com os modelos
"""

config_modelos = {
    'modelo_logisticRegression': {'modelo': LogisticRegression(max_iter=5000), 'dados': X_train_std},
    'modelo_svc': {'modelo': SVC(probability=True), 'dados': X_train_std},
    'modelo_multinomialNB': {'modelo': MultinomialNB(), 'dados': X_train_mm}
}

"""# 3.2 Validação de modelos com Stratified"""

import numpy as np

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def avaliar_modelo(modelo, x, y):
  acuracia, precisao, recall, f1score, auc = [], [], [], [], []

  for train_index, test_index in skf.split(x, y):
    x_train_fold = x.iloc[train_index] if hasattr(x, 'iloc') else x[train_index]
    x_test_fold = x.iloc[test_index] if hasattr(x, 'iloc') else x[test_index]

    y_train_fold = y.iloc[train_index]
    y_test_fold = y.iloc[test_index]

    modelo.fit(x_train_fold, y_train_fold)

    y_pred = modelo.predict(x_test_fold)
    y_proba = modelo.predict_proba(x_test_fold)[:, 1] if hasattr(modelo, "predict_proba") else None

    acuracia.append(accuracy_score(y_test_fold, y_pred))
    precisao.append(precision_score(y_test_fold, y_pred))
    recall.append(recall_score(y_test_fold, y_pred))
    f1score.append(f1_score(y_test_fold, y_pred))

    if y_proba is not None:
      auc.append(roc_auc_score(y_test_fold, y_proba))

  return {
      "Acurácia": np.mean(acuracia),
      "Precisão": np.mean(precisao),
      "Recall": np.mean(recall),
      "F1-Score": np.mean(f1score),
      "AUC": np.mean(auc) if auc else None
  }

resultados = {}

for nome, config in config_modelos.items():
    print(f"Avaliando {nome}...")
    resultados[nome] = avaliar_modelo(config['modelo'], config['dados'], y_train)

"""# 3.3 Resultado dos modelos"""

df_resultados = pd.DataFrame(resultados).T
print(df_resultados)

"""# 3.4 Matriz de confusão de cada modelo"""

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

for i, (nome, config) in enumerate(config_modelos.items()):
      X_eval = X_test_mm if nome == 'modelo_multinomialNB' else X_test_std

      config['modelo'].fit(config['dados'], y_train)

      y_pred = config['modelo'].predict(X_eval)
      cm = confusion_matrix(y_test, y_pred)

      disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Ham', 'Spam'])
      disp.plot(ax=axes[i], cmap='Blues')
      axes[i].set_title(f"Matriz: {nome}")

plt.tight_layout()
plt.show()

"""# 3.5 Curvas ROC"""

fig, ax = plt.subplots(figsize=(7, 5))
palette = sns.color_palette("hls", len(config_modelos))

for i, (model_key, config) in enumerate(config_modelos.items()):
    clf = config['modelo']
    name = model_key.replace('modelo_', '')

    if isinstance(clf, MultinomialNB):
        X_train_model = X_train_mm
        X_test_model = X_test_mm
    else:
        X_train_model = X_train_std
        X_test_model = X_test_std

    clf.fit(X_train_model, y_train)
    y_prob = clf.predict_proba(X_test_model)[:, 1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    auc_v = roc_auc_score(y_test, y_prob)
    ax.plot(fpr, tpr, label=f'{name} (AUC={auc_v:.3f})', color=palette[i], linewidth=2)

ax.plot([0,1],[0,1],'k--', alpha=0.4, label='Random Classifier')
ax.set_xlabel('Taxa de Falsos Positivos (FPR)')
ax.set_ylabel('Taxa de Verdadeiros Positivos (TPR)')
ax.set_title('Curvas ROC - Comparação de Modelos', fontsize=13, fontweight='bold')
ax.legend(fontsize=9)
plt.tight_layout()
plt.show()

"""# Etapa 4 - Análise Comparativa

# 4.1 Identificação e Justificativa do Melhor Modelo de Classificação
"""

best_name = df_resultados['F1-Score'].idxmax()
best_vals = df_resultados.loc[best_name]

best_name_display = best_name.replace('modelo_', '')

print(f"Melhor modelo: {best_name_display.capitalize()}")
print(f"F1-Score: {best_vals['F1-Score']:.4f}")
print(f"AUC-ROC: {best_vals['AUC']:.4f}")
print(f"Acurácia: {best_vals['Acurácia']:.4f}")
print()
print("""
Justificativa:
- A Regressão Logística é o modelo mais indicado para este problema pois apresentou o  melhor desempenho geral, com maior F1-Score e AUC-ROC, mostrando ter um bom equilíbrio entre precisão e recall.

Além disso:
  1. Oferece excelente desempenho com baixo custo computacional comparado ao SVC;
  2. Funciona bem com dados normalizados;
  3. Os coeficientes são interpretáveis permitindo identificar quais palavras/caracteres
     são mais indicativas de spam;
  4. Generaliza bem sem necessidade de tuning extenso.

  O multinamialNB apresentou bom desempenho, porem assume independencia entre features, o que pode limitar sua performance.

  O SVC apresentou resultados competitivos com a Regressãio Logistica porém possui maior custo computacional e menor interpretabilidade.
""")

"""# 4.2 Treinamento final e analise de erros"""

best_clf = LogisticRegression(max_iter=1000, C=1.0, random_state=42)
best_clf.fit(X_train_std, y_train)
y_pred_best = best_clf.predict(X_test_std)
y_prob_best = best_clf.predict_proba(X_test_std)[:,1]

fn_mask = (y_test == 1) & (y_pred_best == 0)
fp_mask = (y_test == 0) & (y_pred_best == 1)

print(f"Falsos Negativos (spam→ham): {fn_mask.sum()}")
print(f"  → Spam não detectado é critico pois pode expor os usuáios a risco de fraude.")
print(f"Falsos Positivos (ham→spam): {fp_mask.sum()}")
print(f"  → E-mail legítimo filtrado incorretamente prejudica a experiencia do usuário.")
print()
print(f"Total de erros: {fn_mask.sum() + fp_mask.sum()} de {len(y_test)} amostras")
print(f"Taxa de erro  : {(fn_mask.sum() + fp_mask.sum())/len(y_test)*100:.2f}%")

"""# 4.3 Análise de importancia de atributos"""

feature_names = x.columns

coef = pd.Series(best_clf.coef_[0], index=feature_names).sort_values()
top_spam = coef.tail(10)
top_ham  = coef.head(10)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

axes[0].barh(top_spam.index, top_spam.values, color='#F44336', alpha=0.85, edgecolor='white')
axes[0].set_title('Top 10 - Indicadores de SPAM', fontweight='bold', color='#F44336')
axes[0].set_xlabel('Coeficiente da Regressão Logística')

axes[1].barh(top_ham.index, top_ham.values, color='#2196F3', alpha=0.85, edgecolor='white')
axes[1].set_title('Top 10 - Indicadores de HAM (Legítimo)', fontweight='bold', color='#2196F3')
axes[1].set_xlabel('Coeficiente da Regressão Logística')

for ax in axes:
    for sp in ['top','right']: ax.spines[sp].set_visible(False)

plt.suptitle('Feature Importance - Regressão Logística', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.show()

print("\nPalavras/caracteres mais indicativos de SPAM:")
for feat, val in top_spam.items():
    print(f"  {feat:35s}: {val:+.3f}")
print("As palavras mais associadas a spam geramente estão relacionadas a promoções, dinheiro e urgencias")
print("\nPalavras/caracteres mais indicativos de HAM:")
for feat, val in top_ham.items():
    print(f"  {feat:35s}: {val:+.3f}")
print("As palavras associadas a ham são mais neutras e comuns em comunicações cotidianas")